// Lista de fotos del álbum de Aida.
//
// Cómo añadir una foto nueva:
// 1. Copia el archivo de imagen dentro de la carpeta images/
// 2. Añade un objeto aquí con:
//      file        -> ruta relativa a la imagen, ej: "images/foto01.jpg"
//      categories  -> array con las personas/etiquetas que aparecen, ej: ["mama", "conmigo"]
//      caption     -> (opcional) un texto o recuerdo corto para esa foto
//
// Las categorías disponibles se detectan automáticamente a partir de las
// que uses aquí, así que puedes inventar las que necesites
// (por ejemplo: "papa", "mama", "conmigo", "amigos", "familia", "cole"...).

const PHOTOS = [
  // --- Primera tanda ---
  { file: "images/aida-06.png", categories: ["papa", "mama"], caption: "" },
  { file: "images/aida-07.png", categories: ["papa"], caption: "La moñi" },
  { file: "images/aida-08.png", categories: ["tia"], caption: "" },
  { file: "images/aida-09.png", categories: ["mama"], caption: "" },
  { file: "images/aida-10.png", categories: ["moni"], caption: "" },
  { file: "images/aida-11.png", categories: ["moni"], caption: "" },
  { file: "images/aida-12.png", categories: ["moni"], caption: "" },
  { file: "images/aida-13.png", categories: ["moni"], caption: "" },
  { file: "images/aida-14.png", categories: ["moni"], caption: "Culerete" },
  { file: "images/aida-15.png", categories: ["moni"], caption: "" },
  { file: "images/aida-16.png", categories: ["moni"], caption: "Gusanito" },
  { file: "images/aida-17.png", categories: ["moni"], caption: "" },
  { file: "images/aida-18.png", categories: ["mama"], caption: "" },
  { file: "images/aida-19.png", categories: ["moni"], caption: "Cristal" },
  { file: "images/aida-20.png", categories: ["tia"], caption: "" },
  { file: "images/aida-21.png", categories: ["mama"], caption: "" },
  { file: "images/aida-22.png", categories: ["mama"], caption: "" },
  { file: "images/aida-23.png", categories: ["moni"], caption: "" },
  { file: "images/aida-24.png", categories: ["guelos"], caption: "" },
  { file: "images/aida-25.png", categories: ["guelos"], caption: "En la playa" },
  { file: "images/aida-26.png", categories: ["guelos"], caption: "" },
  { file: "images/aida-27.png", categories: ["moni"], caption: "" },
  { file: "images/aida-28.png", categories: ["moni"], caption: "" },
  { file: "images/aida-29.png", categories: ["moni"], caption: "" },
  { file: "images/aida-30.png", categories: ["guelos"], caption: "" },
  { file: "images/aida-31.png", categories: ["moni"], caption: "" },
  { file: "images/aida-32.png", categories: ["moni"], caption: "" },
  { file: "images/aida-33.png", categories: ["mama"], caption: "" },
  { file: "images/aida-34.png", categories: ["moni"], caption: "" },
  { file: "images/aida-35.png", categories: ["guelos"], caption: "" },
  { file: "images/aida-36.png", categories: ["jametes"], caption: "" },
  { file: "images/aida-37.png", categories: ["jametes"], caption: "Pesadilla" },
  { file: "images/aida-38.png", categories: ["jametes"], caption: "" },
  { file: "images/aida-39.png", categories: ["jametes", "tia", "guelos"], caption: "" },
  { file: "images/aida-40.png", categories: ["jametes", "mama"], caption: "" },

  // --- Segunda tanda ---
  { file: "images/aida-41.png", categories: ["mama"], caption: "" },
  { file: "images/aida-42.png", categories: ["mama"], caption: "" },
  { file: "images/aida-43.png", categories: ["jametes"], caption: "" },
  { file: "images/aida-44.png", categories: ["moni"], caption: "" },
  { file: "images/aida-45.png", categories: ["jametes"], caption: "" },
  { file: "images/aida-46.png", categories: ["moni"], caption: "" },
  { file: "images/aida-47.png", categories: ["jametes"], caption: "" },
  { file: "images/aida-48.png", categories: ["moni"], caption: "Presidentaaaaa" },
  { file: "images/aida-49.png", categories: ["jametes"], caption: "" },
  { file: "images/aida-50.png", categories: ["jametes"], caption: "" },
  { file: "images/aida-51.png", categories: ["jametes"], caption: "" },
  { file: "images/aida-52.png", categories: ["moni"], caption: "" },
  { file: "images/aida-53.png", categories: ["moni"], caption: "" },
  { file: "images/aida-54.png", categories: ["mama"], caption: "" },
  { file: "images/aida-55.png", categories: ["mama"], caption: "" },
  { file: "images/aida-56.png", categories: ["moni"], caption: "" },
  { file: "images/aida-57.png", categories: ["mama"], caption: "" },
  { file: "images/aida-58.png", categories: ["jametes"], caption: "" },
  { file: "images/aida-59.png", categories: ["jametes", "mama"], caption: "" },
  { file: "images/aida-60.jpeg", categories: ["jametes"], caption: "" },
  { file: "images/aida-61.jpeg", categories: ["jametes"], caption: "" },
  { file: "images/aida-63.jpeg", categories: ["moni"], caption: "" },
  { file: "images/aida-64.jpeg", categories: ["adri"], caption: "" },
  { file: "images/aida-65.jpeg", categories: ["moni"], caption: "Preciosa" },
  { file: "images/aida-66.jpeg", categories: ["mama"], caption: "" },
  { file: "images/aida-67.jpeg", categories: ["moni"], caption: "" },
  { file: "images/aida-68.jpg", categories: ["moni"], caption: "" },
  { file: "images/aida-69.jpg", categories: ["mama", "jametes"], caption: "" },

  // --- Tanda de Adri ---
  { file: "images/aida-70.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-71.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-72.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-73.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-74.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-75.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-76.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-77.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-78.jpg", categories: ["adri"], caption: "Guapooooosss" },
  { file: "images/aida-79.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-80.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-81.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-82.jpg", categories: ["adri"], caption: "" },
  { file: "images/aida-83.jpg", categories: ["papa"], caption: "" },
  { file: "images/aida-84.jpg", categories: ["jametes", "papa"], caption: "" },
  { file: "images/aida-85.jpg", categories: ["papa"], caption: "" },
  { file: "images/aida-86.jpg", categories: ["jametes", "papa"], caption: "" },
  { file: "images/aida-87.jpg", categories: ["papa"], caption: "" },
  { file: "images/aida-88.jpg", categories: ["papa"], caption: "" },
  { file: "images/aida-89.jpg", categories: ["diego", "mama"], caption: "" },
  { file: "images/aida-90.jpg", categories: ["diego", "mama"], caption: "" },
  { file: "images/aida-91.jpg", categories: ["diego", "tia", "mama"], caption: "" },
  { file: "images/aida-92.jpg", categories: ["diego", "tia", "mama"], caption: "" },
  { file: "images/aida-93.jpg", categories: ["diego", "tia", "mama"], caption: "" },
  { file: "images/aida-94.jpg", categories: ["diego", "tia", "mama"], caption: "" },
  { file: "images/aida-95.jpg", categories: ["diego", "tia", "mama"], caption: "" },
  { file: "images/aida-96.jpg", categories: ["diego", "tia", "mama"], caption: "" },
  { file: "images/aida-97.jpg", categories: ["diego", "tia", "mama", "guelos"], caption: "" },
  { file: "images/aida-98.jpg", categories: ["diego"], caption: "" },
  { file: "images/aida-99.jpg", categories: ["diego"], caption: "" },
  { file: "images/aida-100.jpg", categories: ["diego"], caption: "" },
  { file: "images/aida-101.jpg", categories: ["guelos"], caption: "Oza" },
  { file: "images/aida-102.jpg", categories: ["tia", "diego"], caption: "" },
  { file: "images/aida-103.jpg", categories: ["tia"], caption: "" },
  { file: "images/aida-104.jpg", categories: ["tia"], caption: "" },
  { file: "images/aida-105.jpg", categories: ["tia"], caption: "" },
  { file: "images/aida-106.jpg", categories: ["tia", "guelos", "diego", "mama", "jametes"], caption: "" },
  { file: "images/aida-107.jpg", categories: ["guelos", "tia", "mama", "diego"], caption: "" },
  { file: "images/upload-1789494875590.jpg", categories: ["jametes"], caption: "Cumple 2026" },
];

// Nombres bonitos para mostrar en los botones de filtro.
// Si añades una categoría que no está aquí, se mostrará tal cual.
const CATEGORY_LABELS = {
  papa: "Papá",
  mama: "Mamá",
  tia: "Tía",
  moni: "Moñi",
  guelos: "Güelos",
  jametes: "Jametes",
  adri: "Adri",
  diego: "Diego",
};
